name: TFWiki Stats
on:
  schedule:
    - cron: '0 1 * * *' # Run the script daily, the script itself controls which reports are run
  workflow_dispatch:
  pull_request:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # We need full git history to use git merge-base
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: python -u master.py
      timeout-minutes: 180
      env:
        WIKI_USERNAME: ${{ secrets.WIKI_USERNAME }}
        WIKI_PASSWORD: ${{ secrets.WIKI_PASSWORD }}
        PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
      with:
        name: Failed uploads
        path: wiki_*.txt
        if-no-files-found: ignore
